language: generic

jobs:
  include:
    - &OSX_LATEST
      os: osx
      osx_image: xcode12

      env:
      - >
        BREW_NAME="composer@1"
        BREW_LIVECHECK=true

      install:
      - if [ -n "$BREW_TAP" ]; then
          brew tap $BREW_TAP file://$( pwd )/.git;
        fi
      - if [ -n "$BREW_INSTALL" ]; then
          brew install $BREW_INSTALL;
        fi
      - if [ -n "${BREW_CASK}" ]; then
          brew install --cask ${BREW_CASK};
        fi

      before_script:
      - $BREW --version
      - echo "installing ${BREW_TAP}/${BREW_NAME}"
      - travis_retry travis_wait 30 $BREW install ${BREW_TAP}/${BREW_NAME}

      script:
      - if [[ $BREW_LIVECHECK = true ]] && [[ 0 = $(( $TRAVIS_BUILD_NUMBER % $BREW_LIVECHECK_INTERVAL )) ]]; then
          $BREW -v livecheck ${BREW_TAP}/${BREW_NAME};
        fi;
      - if [[ $BREW_TEST = true ]]; then
          $BREW -v test ${BREW_TAP}/${BREW_NAME};
        fi;
      - if [ -n "$TEST_SCRIPT" ]; then
          echo "$TEST_SCRIPT";
          echo "$TEST_SCRIPT" | bash -s;
        fi
      # - if [[ $DEBUG = true ]]; then
      #     $BREW -v uninstall ${BREW_TAP}/${BREW_NAME};
      #   fi

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer@2"
        BREW_LIVECHECK=true

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer1-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer1-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer1-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer1-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-bash-completion"
        BREW_LIVECHECK=true

    - &OSX_PREVIOUS
      <<: *OSX_LATEST
      os: osx
      osx_image: xcode11

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer@2"
        BREW_LIVECHECK=true

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer1-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer1-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer1-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer1-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-bash-completion"
        BREW_LIVECHECK=true

env:
  global:
  - BREW="brew"
  - BREW_TAP="sjorek/php"
  - BREW_INSTALL=""
  - BREW_CASK=""
  - BREW_NAME=""
  - BREW_LIVECHECK=false
  - BREW_LIVECHECK_INTERVAL=1
  - BREW_TEST=false
  - TEST_SCRIPT=""
  - TEST_COMPLETION=""
  # - DEBUG=false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: "YqROjDDNs0KnGIA/q0ntWmqUs7CqY0xiU7neo6o4WlvxmvTxquWcbE46NVtW9VRKwfD+ry/FlRuR60FpSbuE6tzBju+7BGdjJPuvDSnf9I7ip+3waBUclqw+5PSBZs/GQj8hm6UYqEd3GDGs5LMHprPOuDreCaduggz8a+NXFcvw8Pw8h8XwVSkTs8LpOA54v0qGASoWkhBqdruB3JouSCA5h7h049ZeK4n6Nerffj9AVhqvJqlrqrq+//Vq+vzX/6iWcQEP/AYOMbmxY5rWcMHkaxonTzcqesToF895KE90USItEA7V54VMTRgBdkFP1vNlhSvhUG1Gyq3Qte2LfzHSqZv9tx8VtsVUHGRahPTZTPWFbYyDwKl1Pa3gfqIgFwU9Hrp3J99XTG0BgRI2kWBb5DuAmpOdxz6sNZvcOeClQX97MmdHpJreP9QWrUFoaGl3o0AXcT9OBtwZdEfftgUvu9KXZJkgh0Tp1HTVLiMXE1d0hFjxpP5XpZ3nYNTu/2SSuOFY/0PXRtJAM9wf8lUyIWxF2lFe1U/jc9lI3qyxpziaw6Cok9JsB/KLy9i0Zt7G0it7p8SdaWbTGXIaUVyiTYAb9dcEQL24gq1r4n3HnPrg6QUX30OweogUhtVBp1mVM+L8GfsHYhjfN8uUAAEHo6sEwSzaL/4z0Sb99QQ="

