os: osx

language: generic
#language: shell

env:
  global:
  - BREW="brew"
  - BREW_TAP="sjorek/php"
  - BREW_INSTALL=""
  - BREW_CASK=""
  - BREW_NAME=""
  - BREW_LIVECHECK=false
  - BREW_LIVECHECK_INTERVAL=1
  - BREW_TEST=false
  - TEST_SCRIPT=""
  - TEST_COMPLETION=""
  # - DEBUG=false
  matrix:
  - >
    BREW_NAME="composer@1"
    BREW_LIVECHECK=true
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME%@1} --version && (${BREW_NAME%@1} diagnose || true)"
  - >
    BREW_NAME="composer@2"
    BREW_LIVECHECK=true
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME%@2} --version && (${BREW_NAME%@2} diagnose || true)"
  - >
    BREW_NAME="composer-php72"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer-php73"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer-php74"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer-php80"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer2-php72"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer2-php73"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer2-php74"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer2-php80"
    BREW_TEST=true
#    TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"
  - >
    BREW_NAME="composer-bash-completion"
    BREW_TEST=true
    BREW_LIVECHECK=true

install:
- if [ -n "$BREW_TAP" ]; then
    brew tap $BREW_TAP;
  fi
- if [ -n "$BREW_INSTALL" ]; then
    brew install $BREW_INSTALL;
  fi
- if [ -n "${BREW_CASK}" ]; then
    brew install --cask ${BREW_CASK};
  fi

before_script:
- $BREW --version
- echo "installing ${BREW_TAP}/${BREW_NAME}"
- travis_retry travis_wait 30 $BREW install ${BREW_TAP}/${BREW_NAME}

script:
- if [[ $BREW_LIVECHECK = true ]] && [[ 0 = $(( $TRAVIS_BUILD_NUMBER % $BREW_LIVECHECK_INTERVAL )) ]]; then
    $BREW -v livecheck ${BREW_TAP}/${BREW_NAME};
  fi;
- if [[ $BREW_TEST = true ]]; then
    $BREW -v test ${BREW_TAP}/${BREW_NAME};
  fi;
- if [ -n "$TEST_SCRIPT" ]; then
    echo "$TEST_SCRIPT";
    echo "$TEST_SCRIPT" | bash -s;
  fi
# - if [[ $DEBUG = true ]]; then
#     $BREW -v uninstall ${BREW_TAP}/${BREW_NAME};
#   fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: 'OuR57aoy/9mYKAq0lT7aTYWlVBRXoULiptUrzs7vBaUuoIxLz90UOiCAQSA6KetUttCmqTOQJT+YQ4b1hTopQgRyIFrKMF6/6CgYxyGxfNZzTzjZqOs7LGWvZ6U58XGW02wRlFCflVook8uhDo2iF43d68Eky/RdGEwitv7rLBTVGyLRaZ+pXK8MHUR4zcnAT/krchW3pLD3vnn261AnBIIqod3cnhlNQKXkLday25W+z3/0jUuGAyQCDTumfzApAHN0VoDamcni+1fmiSpp/9Ql5NvTbC2DI5znVelsDnQB5Jk7qn31APbhQ+NUdHmJ37QqRhyPUHRnKggtoq2NEsi+reTu5E4UgdScYlZW6MVfLztpAyR35L5Knn6tP9asnkvzR/M/4TlOqpt8+Cga4i5/djcAKgs78xxK7NBIOx3es4ACOidZDJZ0Ym8+loK2KiXiYSUB+IvuD8dKgNicITmtLcBn2J2h1oTVWSG118rj1HPQHZ6r9B5ZGH+EMsCIrWi6EnbD40lXEUYM3TjrQfjvpQ1nXbnMGphRZd6Z6quAtlU6u8UWHCwYGD+5HpO4RT+63ihnYydGsnXkKRJRwQ6B4eRnTy5Xao6+5jKfreiseGvTDwfGgYY9QhKkCCM/Q/JjRTDwCDQ+XDEKocPEeNH/a3K4LC7FnyQruVGctCY='
