language: generic

jobs:
  include:
    - &OSX_LATEST
      os: osx
      osx_image: xcode12

      env:
      - >
        BREW_NAME="composer@1"
        BREW_LIVECHECK=true

      install:
      - if [ -n "$BREW_TAP" ]; then
          brew tap $BREW_TAP file://$( pwd )/.git;
        fi
      - if [ -n "$BREW_INSTALL" ]; then
          brew install $BREW_INSTALL;
        fi
      - if [ -n "${BREW_CASK}" ]; then
          brew install --cask ${BREW_CASK};
        fi

      before_script:
      - $BREW --version
      - echo "installing ${BREW_TAP}/${BREW_NAME}"
      - travis_retry travis_wait 30 $BREW install ${BREW_TAP}/${BREW_NAME}

      script:
      - if [[ $BREW_LIVECHECK = true ]] && [[ 0 = $(( $TRAVIS_BUILD_NUMBER % $BREW_LIVECHECK_INTERVAL )) ]]; then
          $BREW -v livecheck ${BREW_TAP}/${BREW_NAME};
        fi;
      - if [[ $BREW_TEST = true ]]; then
          $BREW -v test ${BREW_TAP}/${BREW_NAME};
        fi;
      - if [ -n "$TEST_SCRIPT" ]; then
          echo "$TEST_SCRIPT";
          echo "$TEST_SCRIPT" | bash -s;
        fi
      # - if [[ $DEBUG = true ]]; then
      #     $BREW -v uninstall ${BREW_TAP}/${BREW_NAME};
      #   fi

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer@2"
        BREW_LIVECHECK=true

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer2-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_LATEST
      env:
      - >
        BREW_NAME="composer-bash-completion"
        BREW_LIVECHECK=true

    - &OSX_PREVIOUS
      <<: *OSX_LATEST
      os: osx
      osx_image: xcode11

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer@2"
        BREW_LIVECHECK=true

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php72"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php73"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php74"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer2-php80"
        TEST_SCRIPT="${BREW_NAME} --version && (${BREW_NAME} diagnose || true)"

    - <<: *OSX_PREVIOUS
      env:
      - >
        BREW_NAME="composer-bash-completion"
        BREW_LIVECHECK=true

env:
  global:
  - BREW="brew"
  - BREW_TAP="sjorek/php"
  - BREW_INSTALL=""
  - BREW_CASK=""
  - BREW_NAME=""
  - BREW_LIVECHECK=false
  - BREW_LIVECHECK_INTERVAL=1
  - BREW_TEST=false
  - TEST_SCRIPT=""
  - TEST_COMPLETION=""
  # - DEBUG=false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: 'tPTv0UTHUdRJJI1en2EEGi3Y3mnNKznO3b1jwL+hetgzXS24ENlxY3zmQgFIdUEK4WqiT+xHoZKRzaL+M4tfeQAPjrr+jQL/NBf1Wj9zHmQn6vs3Bsjqm9Ge86/Jr9DDz6PeNc2V84N0rYe3+KidVex2Dz6g+2pYrBA+qS2AJE9xIkkwaVqEg5SqNPoSqi4Fdt2pB9tBzbNbPIlPulFBOm5QWc/U+vQBBf02BIcyCDNMpUc6opJo+N8zxwwVLCq5InELLRmL2FVMcLCB0bIkdGAH6OmcW1/Qwoq+mEXLN3N4179CuQutgEMPD5X/6jfqCWEoNXl9YfprVLwaiwkz6SijoqoeDPjsMESNM3x+7A+09xZQQg4GII7g0jd2UL9oFmFFSCLaonUSl3FrrqXa25qMyafoHOPAiY4vqvanSY1W+UUWvLNOaD04iG0qb5UbzbBdjWzT/c0sPz4e7FLVdALRDd7df2b0xug9WGgNcTRw6n8hV6I3Dbe69eXWCXvhVL0HUTzZeMKy7kT4p+lh0edVwBbo9G3W82Q4osjJSqWrmC/DbAxGLrA00t8FTFl08HQGZc7yly/3dIhV+vt+Vsm3bULGozbAKyXcahTRc176N9Mj9DrIurebMM+GiLmJGP2Emr8vJW7qtn3AMSwMjs2ZAHpxopzlhZnex4wm8ZY='
